items = [
    "A/C System",
    "Accident",
    "Air Filter",
    "Alternator",
    "Battery",
    "Belts",
    "Body/Chassis",
    "Brake Fluid",
    "Brakes, Front",
    "Brakes, Rear",
    "Cabin Air Filter",
    "Car Wash",
    "Clutch Hydraulic Fluid",
    "Clutch Hydraulic System",
    "Cooling System",
    "Diesel Exhaust Fluid",
    "Differential Fluid",
    "Doors",
    "Engine Antifreeze",
    "Engine Oil",
    "Exhaust System",
    "Fine",
    "Fuel Filter",
    "Fuel Lines & Pipes",
    "Fuel Pump",
    "Fuel System",
    "Glass/Mirrors",
    "Heating System",
    "Horns",
    "Induction",
    "Inspection",
    "Insurance",
    "Lights",
    "Lubricate Chain",
    "MOT",
    "New Tires",
    "Oil Filter",
    "Parking",
    "Payment",
    "Power Steering Fluid",
    "Radiator",
    "Registration",
    "Rust Module",
    "Safety Devices",
    "Spark Plugs",
    "Steering System",
    "Suspension System",
    "Tax",
    "Timing Belt",
    "Tire A",
    "Tire B",
    "Tire C",
    "Tire D",
    "Tire Pressure",
    "Tire Rotation",
    "Tires",
    "Toll",
    "Tow",
    "Transmission Fluid",
    "Water Pump",
    "Wheel Alignment",
    "Windshield Washer Fluid",
    "Windshield Wipers",
]
